# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatroom.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import record_metadata_options_pb2 as record__metadata__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63hatroom.proto\x12\x08\x43hatRoom\x1a\x1drecord_metadata_options.proto\"5\n\x07\x41\x63\x63ount\x12\x11\n\x02id\x18\x01 \x01(\x05\x42\x05\x8aM\x02\x08\x01\x12\x17\n\x08nickname\x18\x02 \x01(\tB\x05\x8aM\x02\x12\x00\"d\n\x07Message\x12\x11\n\x02id\x18\x01 \x01(\x05\x42\x05\x8aM\x02\x08\x01\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\"\n\x07\x61\x63\x63ount\x18\x04 \x01(\x0b\x32\x11.ChatRoom.Account\"f\n\x07\x43hannel\x12\x11\n\x02id\x18\x01 \x01(\x05\x42\x05\x8aM\x02\x08\x01\x12#\n\x08\x61\x63\x63ounts\x18\x02 \x03(\x0b\x32\x11.ChatRoom.Account\x12#\n\x08messages\x18\x03 \x03(\x0b\x32\x11.ChatRoom.Messageb\x06proto3')



_ACCOUNT = DESCRIPTOR.message_types_by_name['Account']
_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_CHANNEL = DESCRIPTOR.message_types_by_name['Channel']
Account = _reflection.GeneratedProtocolMessageType('Account', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNT,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:ChatRoom.Account)
  })
_sym_db.RegisterMessage(Account)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:ChatRoom.Message)
  })
_sym_db.RegisterMessage(Message)

Channel = _reflection.GeneratedProtocolMessageType('Channel', (_message.Message,), {
  'DESCRIPTOR' : _CHANNEL,
  '__module__' : 'chatroom_pb2'
  # @@protoc_insertion_point(class_scope:ChatRoom.Channel)
  })
_sym_db.RegisterMessage(Channel)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACCOUNT.fields_by_name['id']._options = None
  _ACCOUNT.fields_by_name['id']._serialized_options = b'\212M\002\010\001'
  _ACCOUNT.fields_by_name['nickname']._options = None
  _ACCOUNT.fields_by_name['nickname']._serialized_options = b'\212M\002\022\000'
  _MESSAGE.fields_by_name['id']._options = None
  _MESSAGE.fields_by_name['id']._serialized_options = b'\212M\002\010\001'
  _CHANNEL.fields_by_name['id']._options = None
  _CHANNEL.fields_by_name['id']._serialized_options = b'\212M\002\010\001'
  _ACCOUNT._serialized_start=59
  _ACCOUNT._serialized_end=112
  _MESSAGE._serialized_start=114
  _MESSAGE._serialized_end=214
  _CHANNEL._serialized_start=216
  _CHANNEL._serialized_end=318
# @@protoc_insertion_point(module_scope)
