# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: record_metadata_options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
import record_metadata_pb2 as record__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1drecord_metadata_options.proto\x12\x10webaas.db.record\x1a google/protobuf/descriptor.proto\x1a\x15record_metadata.proto\"J\n\rSchemaOptions\x12\x1a\n\x12split_long_records\x18\x03 \x01(\x08\x12\x1d\n\x15store_record_versions\x18\x04 \x01(\x08\"\xbc\x01\n\x0c\x46ieldOptions\x12\x13\n\x0bprimary_key\x18\x01 \x01(\x08\x12\x39\n\x05index\x18\x02 \x01(\x0b\x32*.webaas.db.record.FieldOptions.IndexOption\x1a\\\n\x0bIndexOption\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06unique\x18\x02 \x01(\x08\x12/\n\x07options\x18\x03 \x03(\x0b\x32\x1e.webaas.db.record.Index.Option:N\n\x06schema\x12\x1c.google.protobuf.FileOptions\x18\xd1\t \x01(\x0b\x32\x1f.webaas.db.record.SchemaOptions:M\n\x05\x66ield\x12\x1d.google.protobuf.FieldOptions\x18\xd1\t \x01(\x0b\x32\x1e.webaas.db.record.FieldOptionsb\x06proto3')


SCHEMA_FIELD_NUMBER = 1233
schema = DESCRIPTOR.extensions_by_name['schema']
FIELD_FIELD_NUMBER = 1233
field = DESCRIPTOR.extensions_by_name['field']

_SCHEMAOPTIONS = DESCRIPTOR.message_types_by_name['SchemaOptions']
_FIELDOPTIONS = DESCRIPTOR.message_types_by_name['FieldOptions']
_FIELDOPTIONS_INDEXOPTION = _FIELDOPTIONS.nested_types_by_name['IndexOption']
SchemaOptions = _reflection.GeneratedProtocolMessageType('SchemaOptions', (_message.Message,), {
  'DESCRIPTOR' : _SCHEMAOPTIONS,
  '__module__' : 'record_metadata_options_pb2'
  # @@protoc_insertion_point(class_scope:webaas.db.record.SchemaOptions)
  })
_sym_db.RegisterMessage(SchemaOptions)

FieldOptions = _reflection.GeneratedProtocolMessageType('FieldOptions', (_message.Message,), {

  'IndexOption' : _reflection.GeneratedProtocolMessageType('IndexOption', (_message.Message,), {
    'DESCRIPTOR' : _FIELDOPTIONS_INDEXOPTION,
    '__module__' : 'record_metadata_options_pb2'
    # @@protoc_insertion_point(class_scope:webaas.db.record.FieldOptions.IndexOption)
    })
  ,
  'DESCRIPTOR' : _FIELDOPTIONS,
  '__module__' : 'record_metadata_options_pb2'
  # @@protoc_insertion_point(class_scope:webaas.db.record.FieldOptions)
  })
_sym_db.RegisterMessage(FieldOptions)
_sym_db.RegisterMessage(FieldOptions.IndexOption)

if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(schema)
  google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(field)

  DESCRIPTOR._options = None
  _SCHEMAOPTIONS._serialized_start=108
  _SCHEMAOPTIONS._serialized_end=182
  _FIELDOPTIONS._serialized_start=185
  _FIELDOPTIONS._serialized_end=373
  _FIELDOPTIONS_INDEXOPTION._serialized_start=281
  _FIELDOPTIONS_INDEXOPTION._serialized_end=373
# @@protoc_insertion_point(module_scope)
